#!/usr/bin/env bash
set -euo pipefail
set +u; pattern="$1"; set -u

sudo find /var/log -name "dpkg.*" -print0 \
  | xargs -0 zgrep -Pi '\b(install|remove|upgrade)\b.*'"($pattern)" \
  | sed -E 's/^[^:]+://' \
  | sed -E 's/^(\S+)\s+(\S+)\s+(\S+)\s+([^:]+):(\S+)/\1 \2 \3 :\4: (\5)/g' \
  | sort \
  | grep --color=always -Pi "$pattern" \
  | sed  '1s;^;————— ————— ————— ————— ————— ————— ————— \n;' \
  | sed  '1s;^;Date Time Action Name Arch Previous Current\n;' \
  | column -t -s' ' \
  | less -SR#5 +G



